package com.api.usuario.modelo;

import javax.annotation.PostConstruct;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

@Component
public class ModeloDataLoader {

    @Autowired
    private ModeloRepository modeloRepository;

    @PostConstruct
    @Transactional
    private void loadData() {
    	modeloRepository.truncateTable();
        // Dados dos esportes
    	Object[][] dadosEsportes = {
    		    // Futebol
    			{"","",1},
    			{"Futebol", "Chute", 5},
    			{"Futebol", "Drible", 5},
    			{"Futebol", "Velocidade", 4},
    			{"Futebol", "Controle de bola", 5},
    			{"Futebol", "Passe", 5},
    			{"Futebol", "Visão de jogo", 4},
    			{"Futebol", "Resistência", 3},
    			{"Futebol", "Posicionamento tático", 4},
    			{"Futebol", "Habilidade aérea", 3},
    			{"Futebol", "Marcação", 4},
    			{"Futebol", "Finalização", 5},
    			{"Futebol", "Espírito de equipe", 4},
    			{"Futebol", "Liderança", 4},
    			{"Futebol", "Comunicação", 4},
    			{"Futebol", "Determinação", 4},
    			{"Futebol", "Flexibilidade", 3},
    			{"Futebol", "Força", 4},
    			{"Futebol", "Agilidade", 4},
    			{"Futebol", "Inteligência tática", 4},
    			{"Futebol", "Concentração", 4},
    		    // Vôlei
    			{"Vôlei", "Saque", 4},
    			{"Vôlei", "Bloqueio", 4},
    			{"Vôlei", "Ataque", 4},
    			{"Vôlei", "Defesa", 4},
    			{"Vôlei", "Levantamento", 5},
    			{"Vôlei", "Resistência", 3},
    			{"Vôlei", "Comunicação", 5},
    			{"Vôlei", "Espírito de equipe", 4},
    			{"Vôlei", "Antecipação", 4},
    			{"Vôlei", "Flexibilidade", 3},
    			{"Vôlei", "Estratégia de jogo", 4},
    			{"Vôlei", "Capacidade de decisão", 4},
    			{"Vôlei", "Força", 4},
    			{"Vôlei", "Concentração", 4},
    			{"Vôlei", "Agilidade", 4},
    			{"Vôlei", "Coordenação", 4},
    			{"Vôlei", "Capacidade de salto", 5},
    			{"Vôlei", "Resiliência", 3},
    			{"Vôlei", "Inteligência de jogo", 4},
    			{"Vôlei", "Leitura do adversário", 4},
    		    // Basquete
    			{"Basquete", "Arremesso", 5},
    			{"Basquete", "Drible", 4},
    			{"Basquete", "Rebotes", 4},
    			{"Basquete", "Defesa", 4},
    			{"Basquete", "Visão de jogo", 5},
    			{"Basquete", "Passe", 5},
    			{"Basquete", "Inteligência tática", 4},
    			{"Basquete", "Resistência", 4},
    			{"Basquete", "Velocidade", 4},
    			{"Basquete", "Força física", 4},
    			{"Basquete", "Espírito de equipe", 4},
    			{"Basquete", "Liderança", 4},
    			{"Basquete", "Comunicação", 4},
    			{"Basquete", "Determinação", 4},
    			{"Basquete", "Flexibilidade", 3},
    			{"Basquete", "Agilidade", 4},
    			{"Basquete", "Concentração", 4},
    			{"Basquete", "Capacidade de decisão", 4},
    			{"Basquete", "Resiliência", 3},
    			{"Basquete", "Controle sob pressão", 4},
    		    // Futebol de Areia
    			{"Futebol de Areia", "Chute", 5},
    			{"Futebol de Areia", "Drible", 5},
    			{"Futebol de Areia", "Velocidade", 4},
    			{"Futebol de Areia", "Controle de bola", 5},
    			{"Futebol de Areia", "Passe", 5},
    			{"Futebol de Areia", "Visão de jogo", 4},
    			{"Futebol de Areia", "Resistência", 3},
    			{"Futebol de Areia", "Posicionamento tático", 4},
    			{"Futebol de Areia", "Habilidade aérea", 3},
    			{"Futebol de Areia", "Marcação", 4},
    			{"Futebol de Areia", "Finalização", 5},
    			{"Futebol de Areia", "Espírito de equipe", 4},
    			{"Futebol de Areia", "Liderança", 4},
    			{"Futebol de Areia", "Comunicação", 4},
    			{"Futebol de Areia", "Determinação", 4},
    			{"Futebol de Areia", "Agilidade na areia", 5},
    			{"Futebol de Areia", "Resiliência", 4},
    			{"Futebol de Areia", "Força física", 4},
    			{"Futebol de Areia", "Jogo aéreo", 4},
    			{"Futebol de Areia", "Adaptação ao ambiente", 4},
    		    // Skate
    			{"Skate", "Ollie", 4},
    			{"Skate", "Flip tricks", 5},
    			{"Skate", "Grinds", 4},
    			{"Skate", "Manuals", 3},
    			{"Skate", "Transições", 4},
    			{"Skate", "Velocidade", 3},
    			{"Skate", "Agilidade", 4},
    			{"Skate", "Coordenação corporal", 5},
    			{"Skate", "Controle da prancha", 5},
    			{"Skate", "Criatividade", 5},
    			{"Skate", "Adaptabilidade a diferentes superfícies", 4},
    			{"Skate", "Conhecimento de obstáculos", 4},
    			{"Skate", "Estilo pessoal", 5},
    			{"Skate", "Consistência nas manobras", 4},
    			{"Skate", "Coragem para tentar novas manobras", 5},
    			{"Skate", "Resiliência para superar quedas", 4},
    			{"Skate", "Compreensão do terreno", 4},
    			{"Skate", "Intuição espacial", 4},
    			{"Skate", "Habilidade de execução sob pressão", 4},
    			{"Skate", "Conhecimento da cultura do skate", 4},
    		    // Surfe
    			{"Surfe", "Remada", 4},
    			{"Surfe", "Pegada da onda", 5},
    			{"Surfe", "Posicionamento na água", 4},
    			{"Surfe", "Pop-up", 4},
    			{"Surfe", "Equilíbrio na prancha", 5},
    			{"Surfe", "Manobras básicas", 4},
    			{"Surfe", "Manobras aéreas", 5},
    			{"Surfe", "Velocidade na onda", 5},
    			{"Surfe", "Leitura das condições do mar", 4},
    			{"Surfe", "Escolha de ondas", 4},
    			{"Surfe", "Capacidade de adaptação", 4},
    			{"Surfe", "Resistência física", 4},
    			{"Surfe", "Técnica de surf backside", 4},
    			{"Surfe", "Técnica de surf frontside", 4},
    			{"Surfe", "Conhecimento de segurança no mar", 4},
    			{"Surfe", "Uso eficiente do leash", 3},
    			{"Surfe", "Manutenção do equipamento", 3},
    			{"Surfe", "Estratégia de competição", 4},
    			{"Surfe", "Psicologia de performance", 4},
    			{"Surfe", "Consciência ambiental", 4},
    		    // Tênis
    			{"Tênis", "Saque", 5},
    			{"Tênis", "Forehand", 5},
    			{"Tênis", "Backhand", 5},
    			{"Tênis", "Voleio", 4},
    			{"Tênis", "Smash", 4},
    			{"Tênis", "Drop shot", 4},
    			{"Tênis", "Slice", 4},
    			{"Tênis", "Velocidade de movimento", 4},
    			{"Tênis", "Agilidade", 4},
    			{"Tênis", "Coordenação olho-mão", 5},
    			{"Tênis", "Estratégia de jogo", 5},
    			{"Tênis", "Resistência física", 4},
    			{"Tênis", "Força", 4},
    			{"Tênis", "Concentração", 5},
    			{"Tênis", "Capacidade de adaptação", 4},
    			{"Tênis", "Controle emocional", 4},
    			{"Tênis", "Leitura do adversário", 4},
    			{"Tênis", "Gestão do estresse", 4},
    			{"Tênis", "Posicionamento em quadra", 4},
    			{"Tênis", "Comunicação com o treinador", 3},
    		    // MMA
    		    {"MMA", "Golpes de punho", 5},
    		    {"MMA", "Chutes", 4},
    		    {"MMA", "Joelhadas", 4},
    		    {"MMA", "Cotoveladas", 4},
    		    {"MMA", "Agarres", 4},
    		    {"MMA", "Quedas", 4},
    		    {"MMA", "Defesa de quedas", 4},
    		    {"MMA", "Submissões", 5},
    		    {"MMA", "Jiu-jitsu", 5},
    		    {"MMA", "Muay Thai", 4},
    		    {"MMA", "Boxe", 4},
    		    {"MMA", "Wrestling", 4},
    		    {"MMA", "Taekwondo", 3},
    		    {"MMA", "Karatê", 3},
    		    {"MMA", "Condicionamento físico", 4},
    		    {"MMA", "Resistência cardiovascular", 4},
    		    {"MMA", "Força explosiva", 4},
    		    {"MMA", "Controle de distância", 4},
    		    {"MMA", "Estratégia de luta", 5},
    		    {"MMA", "Preparação mental e emocional", 5},
    		    // Atletismo
    		    {"Atletismo", "Corrida de velocidade", 5},
    		    {"Atletismo", "Corrida de resistência", 4},
    		    {"Atletismo", "Corrida com barreiras", 4},
    		    {"Atletismo", "Salto em altura", 4},
    		    {"Atletismo", "Salto em distância", 4},
    		    {"Atletismo", "Salto triplo", 4},
    		    {"Atletismo", "Arremesso de peso", 3},
    		    {"Atletismo", "Lançamento de disco", 3},
    		    {"Atletismo", "Lançamento de dardo", 3},
    		    {"Atletismo", "Salto com vara", 4},
    		    {"Atletismo", "Hurdles", 4},
    		    {"Atletismo", "Técnica de largada", 4},
    		    {"Atletismo", "Técnica de passagem de bastão", 4},
    		    {"Atletismo", "Flexibilidade", 3},
    		    {"Atletismo", "Força explosiva", 4},
    		    {"Atletismo", "Técnica de corrida", 5},
    		    {"Atletismo", "Resistência muscular", 4},
    		    {"Atletismo", "Controle da respiração", 4},
    		    {"Atletismo", "Foco mental", 5},
    		    {"Atletismo", "Capacidade de recuperação", 4},
    		    // Natação
    		    {"Natação", "Estilos de nado", 5},
    		    {"Natação", "Viradas", 4},
    		    {"Natação", "Saídas", 4},
    		    {"Natação", "Técnica de respiração", 5},
    		    {"Natação", "Técnica de braçada", 5},
    		    {"Natação", "Técnica de pernada", 5},
    		    {"Natação", "Resistência aquática", 4},
    		    {"Natação", "Velocidade", 5},
    		    {"Natação", "Coordenação de movimentos", 4},
    		    {"Natação", "Força muscular", 4},
    		    {"Natação", "Técnica de virada de parede", 4},
    		    {"Natação", "Tática de prova", 4},
    		    {"Natação", "Uso eficiente da água", 4},
    		    {"Natação", "Técnica de mergulho", 4},
    		    {"Natação", "Controle do ritmo de prova", 4},
    		    {"Natação", "Estratégia de respiração", 4},
    		    {"Natação", "Preparação mental para competições", 5},
    		    {"Natação", "Adaptação a diferentes temperaturas da água", 4},
    		    {"Natação", "Capacidade de concentração", 5},
    		    {"Natação", "Resiliência", 4},
    		    // Ginástica Artística
    		    {"Ginástica Artística", "Barra fixa", 4},
    		    {"Ginástica Artística", "Barras paralelas", 4},
    		    {"Ginástica Artística", "Argolas", 4},
    		    {"Ginástica Artística", "Salto sobre o cavalo", 4},
    		    {"Ginástica Artística", "Solo", 5},
    		    {"Ginástica Artística", "Paralelas assimétricas", 4},
    		    {"Ginástica Artística", "Flexibilidade", 4},
    		    {"Ginástica Artística", "Força muscular", 4},
    		    {"Ginástica Artística", "Equilíbrio", 4},
    		    {"Ginástica Artística", "Coordenação motora", 5},
    		    {"Ginástica Artística", "Agilidade", 4},
    		    {"Ginástica Artística", "Concentração", 5},
    		    {"Ginástica Artística", "Técnica de giros", 4},
    		    {"Ginástica Artística", "Técnica de saltos", 4},
    		    {"Ginástica Artística", "Técnica de aterrissagem", 4},
    		    {"Ginástica Artística", "Coreografia", 4},
    		    {"Ginástica Artística", "Resistência física", 4},
    		    {"Ginástica Artística", "Alongamento", 4},
    		    {"Ginástica Artística", "Controle corporal", 4},
    		    {"Ginástica Artística", "Expressão artística", 5},
    		    // Jiu-Jitsu Brasileiro
    		    {"Jiu-Jitsu Brasileiro", "Guarda", 4},
    		    {"Jiu-Jitsu Brasileiro", "Passagem de guarda", 4},
    		    {"Jiu-Jitsu Brasileiro", "Finalizações", 5},
    		    {"Jiu-Jitsu Brasileiro", "Estrangulamentos", 5},
    		    {"Jiu-Jitsu Brasileiro", "Chaves de articulação", 5},
    		    {"Jiu-Jitsu Brasileiro", "Posicionamento no tatame", 4},
    		    {"Jiu-Jitsu Brasileiro", "Defesa pessoal", 4},
    		    {"Jiu-Jitsu Brasileiro", "Técnica de quedas", 4},
    		    {"Jiu-Jitsu Brasileiro", "Técnica de puxadas", 4},
    		    {"Jiu-Jitsu Brasileiro", "Técnica de reversões", 4},
    		    {"Jiu-Jitsu Brasileiro", "Técnica de transições", 4},
    		    {"Jiu-Jitsu Brasileiro", "Técnica de controle", 4},
    		    {"Jiu-Jitsu Brasileiro", "Resistência física", 4},
    		    {"Jiu-Jitsu Brasileiro", "Estratégia de luta", 5},
    		    {"Jiu-Jitsu Brasileiro", "Leitura do oponente", 5},
    		    {"Jiu-Jitsu Brasileiro", "Preparação mental", 5},
    		    {"Jiu-Jitsu Brasileiro", "Conhecimento das regras", 4},
    		    {"Jiu-Jitsu Brasileiro", "Força muscular", 4},
    		    {"Jiu-Jitsu Brasileiro", "Flexibilidade", 4},
    		    {"Jiu-Jitsu Brasileiro", "Capacidade de adaptação", 4},
    		    // Capoeira
    		    {"Capoeira", "Ginga", 4},
    		    {"Capoeira", "Aú", 4},
    		    {"Capoeira", "Chutes", 4},
    		    {"Capoeira", "Defesas", 4},
    		    {"Capoeira", "Ataques", 4},
    		    {"Capoeira", "Esquivas", 4},
    		    {"Capoeira", "Rasteiras", 4},
    		    {"Capoeira", "Acrobacias", 4},
    		    {"Capoeira", "Música e canto", 4},
    		    {"Capoeira", "Cultura e história", 4},
    		    {"Capoeira", "Ritualidade", 4},
    		    {"Capoeira", "Respeito ao mestre", 5},
    		    {"Capoeira", "Respeito ao oponente", 5},
    		    {"Capoeira", "Habilidade de improvisação", 5},
    		    {"Capoeira", "Expressão artística", 5},
    		    {"Capoeira", "Disciplina", 5},
    		    {"Capoeira", "Resiliência", 4},
    		    {"Capoeira", "Autoconfiança", 4},
    		    {"Capoeira", "Adaptação ao ritmo do jogo", 4},
    		    {"Capoeira", "Estratégia de jogo", 4},
    		    // Ciclismo
    		    {"Ciclismo", "Resistência cardiovascular", 5},
    		    {"Ciclismo", "Força nas pernas", 4},
    		    {"Ciclismo", "Resistência muscular", 4},
    		    {"Ciclismo", "Velocidade", 4},
    		    {"Ciclismo", "Agilidade", 3},
    		    {"Ciclismo", "Técnica de pedalada", 4},
    		    {"Ciclismo", "Controle da bicicleta", 4},
    		    {"Ciclismo", "Subidas", 4},
    		    {"Ciclismo", "Descidas", 4},
    		    {"Ciclismo", "Estratégia de corrida", 4},
    		    {"Ciclismo", "Equipamentos e manutenção da bicicleta", 4},
    		    {"Ciclismo", "Navegação em percursos", 3},
    		    {"Ciclismo", "Noções de mecânica básica", 3},
    		    {"Ciclismo", "Técnica de curva", 4},
    		    {"Ciclismo", "Posicionamento aerodinâmico", 4},
    		    {"Ciclismo", "Alimentação e hidratação durante o percurso", 4},
    		    {"Ciclismo", "Conhecimento das regras de trânsito", 3},
    		    {"Ciclismo", "Trabalho em equipe", 3},
    		    {"Ciclismo", "Mentalidade competitiva", 4},
    		    {"Ciclismo", "Gestão do esforço ao longo da prova", 5},
    		    // Boxe
    		    {"Boxe", "Jabs", 4},
    		    {"Boxe", "Cross", 4},
    		    {"Boxe", "Hooks", 4},
    		    {"Boxe", "Uppercuts", 4},
    		    {"Boxe", "Esquivas", 4},
    		    {"Boxe", "Guarda", 4},
    		    {"Boxe", "Footwork", 4},
    		    {"Boxe", "Condicionamento físico", 5},
    		    {"Boxe", "Resistência cardiovascular", 4},
    		    {"Boxe", "Força explosiva", 4},
    		    {"Boxe", "Velocidade de golpe", 4},
    		    {"Boxe", "Técnica de combinação de golpes", 4},
    		    {"Boxe", "Técnica de bloqueio", 4},
    		    {"Boxe", "Estratégia de luta", 5},
    		    {"Boxe", "Controle emocional", 4},
    		    {"Boxe", "Leitura do oponente", 4},
    		    {"Boxe", "Condição mental", 4},
    		    {"Boxe", "Resiliência", 4},
    		    {"Boxe", "Disciplina", 4},
    		    {"Boxe", "Respeito pelo adversário", 5},
    		    // Tênis de Mesa
    		    {"Tênis de Mesa", "Saque", 4},
    		    {"Tênis de Mesa", "Forehand", 4},
    		    {"Tênis de Mesa", "Backhand", 4},
    		    {"Tênis de Mesa", "Drive", 4},
    		    {"Tênis de Mesa", "Smash", 4},
    		    {"Tênis de Mesa", "Efeito", 4},
    		    {"Tênis de Mesa", "Controle de bola", 4},
    		    {"Tênis de Mesa", "Velocidade de reação", 4},
    		    {"Tênis de Mesa", "Coordenação olho-mão", 4},
    		    {"Tênis de Mesa", "Agilidade", 4},
    		    {"Tênis de Mesa", "Tática de jogo", 4},
    		    {"Tênis de Mesa", "Estratégia de ponto", 4},
    		    {"Tênis de Mesa", "Variação de efeito", 4},
    		    {"Tênis de Mesa", "Controle de distância", 4},
    		    {"Tênis de Mesa", "Movimentação na mesa", 4},
    		    {"Tênis de Mesa", "Resistência física", 4},
    		    {"Tênis de Mesa", "Concentração", 5},
    		    {"Tênis de Mesa", "Determinação", 5},
    		    {"Tênis de Mesa", "Preparação mental", 5},
    		    {"Tênis de Mesa", "Fair play", 5},
    		    // Handebol
    		    {"Handebol", "Arremesso", 5},
    		    {"Handebol", "Recepção", 4},
    		    {"Handebol", "Passe", 4},
    		    {"Handebol", "Drible", 4},
    		    {"Handebol", "Defesa", 4},
    		    {"Handebol", "Ataque", 4},
    		    {"Handebol", "Rápida transição defesa-ataque", 4},
    		    {"Handebol", "Visão de jogo", 4},
    		    {"Handebol", "Agilidade", 4},
    		    {"Handebol", "Resistência física", 4},
    		    {"Handebol", "Resistência mental", 4},
    		    {"Handebol", "Técnica de marcação", 4},
    		    {"Handebol", "Leitura de jogadas", 4},
    		    {"Handebol", "Trabalho em equipe", 5},
    		    {"Handebol", "Comunicação em quadra", 5},
    		    {"Handebol", "Liderança", 5},
    		    {"Handebol", "Estratégia de jogo", 5},
    		    {"Handebol", "Disciplina tática", 5},
    		    {"Handebol", "Fair play", 5},
    		    {"Handebol", "Capacidade de finalização sob pressão", 4},
    		    // Automobilismo
    		    {"Automobilismo", "Velocidade", 5},
    		    {"Automobilismo", "Habilidade na pilotagem", 5},
    		    {"Automobilismo", "Conhecimento técnico do veículo", 4},
    		    {"Automobilismo", "Coragem", 5},
    		    {"Automobilismo", "Técnica de ultrapassagem", 4},
    		    {"Automobilismo", "Estratégia de corrida", 5},
    		    {"Automobilismo", "Adaptação às condições da pista", 4},
    		    {"Automobilismo", "Concentração", 5},
    		    {"Automobilismo", "Resistência física", 4},
    		    {"Automobilismo", "Resistência mental", 4},
    		    {"Automobilismo", "Compreensão das regras de corrida", 4},
    		    {"Automobilismo", "Trabalho em equipe (no caso de corridas de equipe)", 5},
    		    {"Automobilismo", "Comunicação com a equipe durante a corrida", 5},
    		    {"Automobilismo", "Rápida tomada de decisão", 4},
    		    {"Automobilismo", "Gerenciamento de riscos", 5},
    		    {"Automobilismo", "Estratégia de pits", 4},
    		    {"Automobilismo", "Técnica de frenagem", 4},
    		    {"Automobilismo", "Adaptação a diferentes circuitos", 4},
    		    {"Automobilismo", "Conhecimento do veículo em condições adversas", 4},
    		    {"Automobilismo", "Técnica de largada", 4},
    		    // Rugby
    		    {"Rugby", "Passe", 4},
    		    {"Rugby", "Chute", 4},
    		    {"Rugby", "Tackle", 5},
    		    {"Rugby", "Ruck", 5},
    		    {"Rugby", "Scrum", 5},
    		    {"Rugby", "Line-out", 5},
    		    {"Rugby", "Maul", 5},
    		    {"Rugby", "Finta", 4},
    		    {"Rugby", "Velocidade", 4},
    		    {"Rugby", "Força física", 5},
    		    {"Rugby", "Resistência", 5},
    		    {"Rugby", "Agilidade", 4},
    		    {"Rugby", "Inteligência tática", 5},
    		    {"Rugby", "Trabalho em equipe", 5},
    		    {"Rugby", "Liderança", 5},
    		    {"Rugby", "Disciplina", 5},
    		    {"Rugby", "Fair play", 5},
    		    {"Rugby", "Espírito esportivo", 5},
    		    {"Rugby", "Capacidade de leitura do jogo", 5},
    		    {"Rugby", "Habilidade de decisão", 5},
    		    // Patinação no Gelo/Artística
    		    {"Patinação no Gelo/Artística", "Giro", 5},
    		    {"Patinação no Gelo/Artística", "Salto", 5},
    		    {"Patinação no Gelo/Artística", "Coreografia", 5},
    		    {"Patinação no Gelo/Artística", "Expressão artística", 5},
    		    {"Patinação no Gelo/Artística", "Técnica de patinação", 5},
    		    {"Patinação no Gelo/Artística", "Coordenação", 5},
    		    {"Patinação no Gelo/Artística", "Estabilidade", 4},
    		    {"Patinação no Gelo/Artística", "Flexibilidade", 4},
    		    {"Patinação no Gelo/Artística", "Força muscular", 4},
    		    {"Patinação no Gelo/Artística", "Resiliência", 4},
    		    {"Patinação no Gelo/Artística", "Determinação", 4},
    		    {"Patinação no Gelo/Artística", "Disciplina", 4},
    		    {"Patinação no Gelo/Artística", "Preparação física", 4},
    		    {"Patinação no Gelo/Artística", "Preparação mental", 5},
    		    {"Patinação no Gelo/Artística", "Respeito pelos juízes", 5},
    		    {"Patinação no Gelo/Artística", "Musicalidade", 5},
    		    {"Patinação no Gelo/Artística", "Interpretação da música", 5},
    		    {"Patinação no Gelo/Artística", "Conexão com o público", 4},
    		    {"Patinação no Gelo/Artística", "Uso do espaço na pista", 4},
    		    {"Patinação no Gelo/Artística", "Consistência de performance", 4},
    		};

        // Inserir os dados na tabela "modelo"
        for (Object[] dados : dadosEsportes) {
            String esporte = (String) dados[0];
            String parametro = (String) dados[1];
            int peso = (int) dados[2];
            Modelo modelo = new Modelo(esporte, parametro, peso);
            modeloRepository.save(modelo);
        }
    }
}

